- libexec/rc/rc.d/routing
In 3693d9140e05aba9942232df13468f51a6cde136 /etc/rc switched to using find_system_scripts rather than directly including /etc/rc.d/* in the list of scripts to run in order to skip .pkgsave files.  Follow suit in etc/rc.d/routing.
> etc/rc.d/routing: use find_system_scripts

- lib/libsys/intro.2
This patch is currently incorrect until filesystems are moved to section 4.
Does this make the creation of the files section in previous pr redundant?
Is it correct for me here to use "reported by"?
Thanks!
> intro.2: add syscall.h to synopsis & mention emfile vars

- share/man/man5/rc.conf.5
It's not 1996 anymore, and we use CIDR nowadays.  Update the various ifconfig_ examples to use CIDR notation instead of netmasks, and also add an example of a basic ifconfig_ entry that most users will be interested in.
> rc.conf.5: modernise network_interfaces

- usr.sbin/arp/arp.8
The arp.8 manpage documents 'arp -d <addr> pub', but the 'pub' flag is not accepted by the arp command.  Remove this incorrect documentation.
> arp.8: don't document a syntax that doesn't exist

- sys/modules/ice_ddp/Makefile
- sys/modules/qatfw/qat_200xx/Makefile
- sys/modules/qatfw/qat_4xxx/Makefile
- sys/modules/qatfw/qat_c3xxx/Makefile
- sys/modules/qatfw/qat_c4xxx/Makefile
- sys/modules/qatfw/qat_c62x/Makefile
- sys/modules/qatfw/qat_dh895xcc/Makefile
Use .PATH & bare filename. This prevents the real source path from being included in the built object, which improves reproducibility.
> Address module reproducibility issues

- contrib/elftoolchain/libelftc/libelftc_dem_gnu3.c
- contrib/libcxxrt/libelftc_dem_gnu3.c
The __cxa_demangle_gnu3() and cpp_demangle_gnu3() functions segfault on various libcxxabi test cases due to a copy and paste error. This change fixes that.
> Fix memory corruption in C++ demangler

- share/man/man4/ahc.4
- sys/dev/aic7xxx/ahc_pci.c
- sys/powerpc/conf/GENERIC
- sys/powerpc/conf/GENERIC64
- sys/powerpc/conf/GENERIC64LE
When this driver was written it made sense to make this default to off, but these days almost all BIOSses will do the right thing. Furthermore non-mmio communication only works on Intel architectures.
So lets default to allowing mmio, but not change the semantics of the `AHC_ALLOW_MEMIO` flag to not break existing installs. Also document the already existing `hint.ahc.<unit>.allow_memio`.
> ahc(4): Default to memory mapped IO

- include/sysexits.h
- share/man/man3/sysexits.3
I was originally intending to rewrite intro.1 but then I thought it really needs to go in sysexits.{3/h}. Is my syntax for the commit log correct? Some of these sentences are verbatim not mine.
Thank you so much for going out of your way to include me in this game, it's really enriching my life and very meaningful to me.
> sysexits: tidy deprecated header and manual

- libexec/atrun/atrun.man
- usr.sbin/cron/crontab/crontab.5
Fix https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243380
> at cron file now lives in /etc/cron.d/at

- sys/compat/linux/linux_misc.c
Current handling of the SIGPENDING & MSGQUEUE rlimits just return infinity.
Adjust it to match to what linprocfs already does in [sys/compat/linprocfs/linprocfs.c](https://github.com/freebsd/freebsd-src/blob/main/sys/compat/linprocfs/linprocfs.c#L1913)
Ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278893
> linux: Adjust rlimit SIGPENDING & MSGQUEUE behaviour to match linprocfs

- CONTRIBUTING.md
+ move Lua to alphabetize subsections
+ trim 'please' from 'lua: see style'
I love politeness but its inconsistent here* and doesn't make sense.
+ word manpages like other subsections
This promotes consistency and visibility of the style guide, while keeping it clear that our manuals are written in mdoc(7).
+ man PR's shouldn't bump document date
MFC after: (maybe MFC to BETA3 along w/ e7ff917057ea will fix style.mdoc(5) visibility?)
*: but if we want to use please on all of them, say the word
> CONTRIBUTING.md/style: spring cleaning

- sys/kern/kern_intr.c
While otherwise a handy potential approach, getting the trap frame via the argument isn't documented and isn't supposed to be used.  With all uses removed, now remove support to end the mixed calling conventions.
Differential Revision: https://reviews.freebsd.org/D37688
> kern/intr: remove support for passing trap frame as argument

- bin/rmdir/rmdir.1
- bin/rmdir/rmdir.c
- bin/rmdir/tests/rmdir_test.sh
PR: [277677](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277677)
Signed-off-by: henrichhartzer@tuta.io
> /bin/rmdir: Exit with status 2 for invalid arguments

- usr.bin/netstat/nhops.c
- usr.bin/netstat/route.c
The previous width of Netif (10 or 8) was too short for modern interface names; make it 12, which is long enough to display "epair0a.1000".
This came up in practice with genet(4) interfaces, since the base interface name is long enough that with the previous limit, VLAN identifiers would be truncated at 1 character in the IPv6 output: "genet0.100" becomes "genet0.1".
The width is now fixed, and doesn't depend on the address family, because there's no reason that length of the interface name would vary based on the AF.
> netstat(1): increase width of Netif column

- sys/modules/Makefile
- usr.sbin/bhyve/bhyverun.c
In bhyve_parse_config_option(), a string is allocated and passed to nvlist_add_string() but not free'd afterwards.
Reported by:	Coverity
CID:		1544049
> bhyve: avoid resource leak

- usr.sbin/bhyve/bhyverun.c
- usr.sbin/ctladm/ctladm.c
The str variable in cctl_nvlist_end_element() does not get free()'d when converted to an integer value. (name is "trtype")
Reported by:	Coverity Scan
Coverity ID:	1545039
> ctladm: fix resource leak

- lib/libnvmf/nvmf_host.c
- share/man/man4/smb.4
- share/man/man4/smbfs.4
- share/man/man4/unionfs.4
- usr.sbin/autofs/auto_master.5
- usr.sbin/autofs/automount.8
- usr.sbin/autofs/automountd.8
- usr.sbin/autofs/autounmountd.8
In nvmf_host_fetch_discovery_log_page(), the log variable may have been allocated on the heap during a first loop cycle, and should be free()'d again before exiting upon errors.
Reported by:	Coverity
CID:		1545034
> libnvmf: avoid resource leak

- lib/libnvmf/nvmf_host.c
- share/man/man4/smb.4
- share/man/man4/smbfs.4
- share/man/man4/unionfs.4
- usr.sbin/autofs/auto_master.5
- usr.sbin/autofs/automount.8
- usr.sbin/autofs/automountd.8
- usr.sbin/autofs/autounmountd.8
When a macro is used in the list argument, it breaks the formatting. Thus, this is just (polish) a trivial undocumented bug fix for the markup of these pages (plus spdx tag because that seems okay to combine in one commit?).
MFC to 14.1-BETA with fc8ac5fedf7e?
> autofs manuals: re-align lists

- lib/libc/gen/exec.3
- usr.bin/posixmqcontrol/posixmqcontrol.1
I discovered these mistakes by running `git grep -F '.Fx 15'` against the `releng/14.1` branch.
Please merge these changes to `stable/14` and `releng/14.1`.
> Fix "version introduced" in two manual pages

- bin/cp/utils.c
In copy_file(), make sure the from_fd file descriptor is closed even when the operation failed early.
Reported by:	Coverity Scan
CID:		1545036
> cp: avoid a resource leak

- usr.sbin/arp/arp.c
arp(8) usually disallows adding a static ARP entry for an IP address which is not configured on a local interface.
Change this to allow such ARP entries to be added if '-i' is provided to specify the interface the ARP entry relates to.
Due to limitations in the kernel lltable, this still requires that a host route exists for the target address, but allows static ARP entries to be configured to proxy ARP for, e.g., local jails which use an IPv4 address with a /32 route.
---
cc @glebius 
this PR came about from my attempts to make proxy ARP work in FreeBSD -- i still couldn't get it to work for my purposes even with this PR, but i think this is useful even so.
> arp(8): allow -i with -s

- sys/amd64/conf/FIRECRACKER
- sys/amd64/conf/MINIMAL
- sys/i386/conf/MINIMAL
PR: [231768](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231768)
> Remove COMPAT_FREEBSD4/5/6/7/9 from MINIMAL and FIRECRACKER kernel configurations

- sys/netinet/icmp6.h
- usr.sbin/rtadvd/config.c
- usr.sbin/rtadvd/rtadvd.conf.5
- usr.sbin/rtadvd/rtadvd.h
the first commit adds the necessary icmp6.h bits, the second is the implementation in rtadvd.
> rtadvd(8): support PREF64 (RFC 8781)

- sys/netinet/cc/cc_cdg.c
- sys/netinet/cc/cc_chd.c
- sys/netinet/cc/cc_hd.c
- sys/netinet/icmp6.h
Related: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277655
Signed-off-by: henrichhartzer@tuta.io
> sys/netinet/cc: Switch from deprecated random() to prng32()

- sbin/dhclient/dhcpd.h
Its last use was removed in 396c7521364.
Also see: https://reviews.freebsd.org/D42717
> dhclient: remove unused primary_address

- sys/amd64/conf/LINT-NOINET
- sys/amd64/conf/LINT-NOINET6
- sys/modules/Makefile
also includes a required fix for the ipfw module after this change.
tested both kernel configs with buildkernel on amd64.
> improve LINT-NOINET{6,}

- sys/netlink/netlink_snl.h
- sys/netlink/netlink_snl_route.h
- sys/netlink/netlink_snl_route_parsers.h
Trying to fix the errors of [Bug 279054 - Compile failure when #include <netlink/netlink_snl.h> in C++ code (edit)](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279054)
> fix C++ compile errors (FreeBSD-current)

- libexec/rc/rc.subr
- share/man/man8/rc.subr.8
Reload is used for service reconfiguration as well and lacks a NAME_prepend-like mechanism so it makes sense to extend the NAME_reload hook into this
action.
precmd may use configuration checks and blocks setup from doing its designated work (e.g. nginx).  In moving the invoke of the setup script in front allows us to provide custom scripts for config file generation and fixing prior to precmd checking configuration integrity.
Also introduce _run_rc_setup to separate the launcher from the main one.  Let it run correctly in the case of restart_precmd and block further execution as
would be the case in start due to the internal plumbing of restart being split into calling stop and start afterwards.
Also see: https://reviews.freebsd.org/D36259
> rc: improve NAME_setup handling

- libexec/rc/rc.subr
At the moment, if bootrace profiling is enabled, autoboot is not exported to the rc scripts. This causes fsck to not check the root filesystem.  See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278993
> export $autoboot var when running from $boottrace_cmd to fix root check root check if boottrace is enabled

- usr.sbin/bhyve/amd64/pci_gvt-d.c
In a normal code path while setting up GPU passthrough, the size parameter to munmap() is wrong and its operation not checked for errors, therefore leaking resources.
Reported by:	Coverity Scan
CID:		1519830
> bhyve: correctly remove a memory mapping

- contrib/smbfs/mount_smbfs/mount_smbfs.8
- contrib/smbfs/smbutil/smbutil.1
- share/man/man5/nsmb.conf.5
Not sure if it's sane to remove the "resource" keyword from mount_smbfs,
but with this change mount_smbfs will look more like the other mount tools.
Also all of our SMB1 stuff will have consistent descriptions and respond intelligently to "apropos {server message block, CIFS, SMB}".
Tested on our beautiful standard console, nothing wraps.
I trimmed one /$FreeBSD$ and added one SPDX, that's all I could do with that.
Lately I'm wondering if it's appropriate for me to make noise about that in commit log?
Rationale: I like our SMB1/CIFS driver, and tooling previously hard to distinguish from SMBus
MFC after: 3 days
> smbfs manuals: describe consistently

- contrib/smbfs/mount_smbfs/mount_smbfs.8
- contrib/smbfs/smbutil/smbutil.1
- share/man/man4/iicsmb.4
- share/man/man4/smb.4
- share/man/man5/nsmb.conf.5
I'm sorry I didn't realize this last round.
This and the other PR finishes the description differentiation for "apropos smb"
Fixes: 5ad3b09f2fe9 (smb: distinguishable descriptions)
MFC after: 3 days
Related: https://www.reddit.com/r/ProgrammerHumor/comments/1ci0me1/welp/
> smbus manuals: include term SMBus in description

- sbin/mdconfig/mdconfig.c
- sbin/mdconfig/tests/mdconfig_test.sh
MFC with:	b01988d5e570158534110ca309fe93112c5c62f1
Sponsored by:	Axcient
> mdconfig: don't print NUL in the options list

- stand/common/commands.c
The longest command we have is "efi-autoresizecons". That combined with the two spaces before and after the command gives us a total of 23 characters including the null-terminator.
Increasing this caused alignment issues since `efi-autoresizecons` is > 15 chars ("%-15s"). So I also increased that to 20 and removed the two spaces at the end since they aren't really needed.
Before:
```
Available commands:
copy_staging     copy staging
staging_slop     set staging slop
efi-autoresizeconEFI Auto-resize Console <-- Cuts off
gop              graphics output protocol
uga              universal graphics adapter
efi-seed-entropy try to get entropy from the EFI RNG
poweroff         power off the system
...
```
After:
```
Available commands:
copy_staging        copy staging
staging_slop        set …
```
> loader: Increase buffer size to accommodate longer commands

- sys/kern/subr_prf.c
The signedness of "char" is implementation-dependent.
> Fix "%hhi" conversion for kvprintf()

- sys/dev/virtio/p9fs/virtio_p9fs.c
- sys/modules/mpi3mr/Makefile
Stop forcing -g in mpi3mr module because it breaks non-debug install.
> Stop forcing -g in mpi3mr module because it breaks non-debug install.

- sys/dev/virtio/p9fs/virtio_p9fs.c
When the module is loaded on a system running on qemu/kvm the "modern" virtio infrastructure is used and virtio_read_device_config() will end up calling vtpci_modern_read_dev_config(). This function cannot read values of arbitrary sizes and will panic if the p9fs mount tag size is not supported by it.
Use virtio_read_device_config_array() instead. It was tested on both bhyve and qemu/kvm.
PR:	280098
Co-authored-by:	Mark Peek <mp@FreeBSD.org>
Please see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280098 for more details on the investigation.
> virtio_p9fs: fix panic on qemu/kvm

- usr.sbin/fwget/pci/pci_video_amd
This GPU is found in Ryzen 7000 series CPUs.
For future reference, the list of firmware versions for amdgpu drivers can be found in [1].
[1] - https://docs.kernel.org/gpu/amdgpu/driver-misc.html
Notes:
Without this set of firmwares installed, loading the amdgpu driver will cause a kernel panic.
This is my GPU:
```
vgapci0@pci0:11:0:0:    class=0x030000 rev=0xc1 hdr=0x00 vendor=0x1002 device=0x164e subvendor=0x1043 subdevice=0x8877                                                                                                                         
vendor     = 'Advanced Micro Devices, Inc. [AMD/ATI]'                                                                                                                                                                                      
device …
```
> fwget: add needed firmware for AMD Raphael GPUs

- usr.sbin/freebsd-update/freebsd-update.sh
- usr.sbin/fwget/pci/pci_video_amd
The command [openssl-rsautl(1)](https://www.openssl.org/docs/man1.1.1/man1/rsautl.html) has been deprecated in OpenSSL 3.0.  The [openssl-pkeyutl(1)](https://www.openssl.org/docs/man3.1/man1/openssl-pkeyutl.html) command should be used instead.
> freebsd-update: rsautl is deprecated, use pkeyutl

- sys/dev/bnxt/bnxt_en/bnxt.h
- sys/dev/bnxt/bnxt_en/if_bnxt.c
This commit enables NPAR support for Broadcom 57504 10/25GbE NICs.
I've tested this patch against a live 14.1-RELEASE system that were initially unable to detect a driver for the cards and after the changes it detected and worked as expected.
That's the results:
`pciconf -lv`:
```
bnxt0@pci0:0:8:0:	class=0x020000 rev=0x12 hdr=0x00 vendor=0x14e4 device=0x1801 subvendor=0x17aa subdevice=0x4050
vendor     = 'Broadcom Inc. and subsidiaries'
device     = 'BCM57504 NetXtreme-E Ethernet Partition'
class      = network
subclass   = ethernet
bnxt1@pci0:0:9:0:	class=0x020000 rev=0x12 hdr=0x00 vendor=0x14e4 device=0x1801 subvendor=0x17aa subdevice=0x4050
vendor     = 'Broadcom Inc. and subsidiaries'
device     = 'BCM57504 NetXtreme-E Ethernet Partition'
class      = network
subclass   = ethernet
``` …
> /sys/dev/bnxt: Enable NPAR support on BCM57504

- usr.bin/ncal/ncal.1
- usr.bin/ncal/ncal.c
As you can find, FreeBSD cal(1) man page says that
> It is not possible to display Monday as the first day of the week with cal.
But daily it is more comfortable if weeks start from Monday.
I know that there is ncal (vertical) mode which always starts from Monday,
but any other calendar in the world (software or that on the wall) is horizontal,
so ncal is uncomfortable too.
So I've made a simple patch that adds -M option to cal(1) to start week from Monday.
Tried to make as minimal changes to original code as possible.
> Add -M option to display Monday as the first day of the week in cal(1)

- sbin/conscontrol/conscontrol.8
- share/man/man4/vt.4
- usr.sbin/kbdcontrol/kbdcontrol.1
- usr.sbin/kbdmap/kbdmap.1
- usr.sbin/moused/moused.8
- usr.sbin/vidcontrol/vidcontrol.1
I'm trying to make "apropos -s 1 keyboard" and "console" look nice and tell the console user what they're probably looking for, while distinguishing what they're not looking for (graphical environment tooling, serial console tooling, I dont know). Patches sent to freedesktop and libxkbcommon for that effect too. EDIT: all patches upstream accepted.
~~But, pointy hat to me: my proposed vidfont description is 81 characters. This wraps in man, which I think looks fine, but wraps in apropos, which looks horrible, on 80 char "standard console" including stock xterm; seems unacceptable regression. Ideas?~~
I don't know how it is on other people's boxen but in my house terminus bsd console (vt) is 85 char wide and is unaffected by this proposed regression.
> manuals: improve apropos {console, keyboard}

- stand/defaults/loader.conf.5
- stand/efi/libefi/efi_console.c
The UEFI spec says:
> It is required that all output devices support at least 80x25 text mode. This mode is defined to be mode 0.
So change the EFI `TEXT_ROWS` macro to reflect this. This also makes it more inline with the BIOS version:
https://github.com/freebsd/freebsd-src/blob/d19851f002862a5510bf31fae4083fab979258be/stand/i386/libi386/vbe.h#L136
Also clarify the man page. The only time we have a fixed resolution terminal is in text mode with the BIOS loader, and that uses 80x25. With the other configurations, the terminal size isn't really guaranteed to be anything.
> loader: Correct terminal size

- sys/dev/cxgb/cxgb_sge.c
This test here appears to be clamping the start and stop values to a minimum and maximum. But it looks like one of these lines may have been copied incorrectly.
This code pattern is probably intended to test both start and stop against sensible values, but accidentally only changes the start value.
looking at the logic, I suspect that the impact of this bug might be negligible in most cases since it would simply reduce the performance impact of packet coalescing by avoiding aggressive start values.
> Potential typo/copy issue

- share/man/man7/networking.7
- sys/fs/p9fs/p9fs_vnops.c
`service routing restart` isn't necessary and actually breaks routing.
Fixes:		75eda009
MFC after:	3 days
Reported by:	Graham Perrin
> networking.7: erase confusing caveat

- share/man/man7/networking.7
- sys/fs/p9fs/p9fs_vnops.c
This code is using the vnode after it has been released and causing a panic when a p9fs shared volume is unmounted. In fact, it seems like it's just duplicated code left behind from a bad merge.
PR:		279887
Reported by:	Michael Dexter
---
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279887 for more details.
It seems to me that this code originated from here https://github.com/Juniper/virtfs/blob/jnpr/virtfs/sys/dev/virtio/9pfs/virtfs_vnops.c#L97
With this patch I can mount/umount p9fs shares reliably.
Feedback from someone familiar with the code would be appreciated.
> p9fs: remove duplicated code

- bin/test/test.c
- etc/mtree/BSD.include.dist
- etc/mtree/BSD.tests.dist
- sbin/adjkerntz/adjkerntz.8
- sys/dev/gpio/bytgpio.c
- usr.bin/netstat/netstat.1
- usr.sbin/pw/pw.8
I had a script where I forgot a space before the closing bracket of a test statement and the resulting error was this:
[: missing ]
Somehow my brain thought that this was something printed in brackets and  that a colon was missing. I propose to change the message to
[: missing ']'
to make it less likely that such a confusion occurs.
This is also what others are doing:
Coreutils test:
[: missing ']'
Bash:
bash: [: missing `]'
Zsh:
[: ']' expected
> test(1): quote closing bracket in error message

- bin/test/test.c
- etc/mtree/BSD.include.dist
- etc/mtree/BSD.tests.dist
- sbin/adjkerntz/adjkerntz.8
- sys/dev/gpio/bytgpio.c
- usr.bin/netstat/netstat.1
- usr.sbin/pw/pw.8
```bash
mkdir /tmp/MTREE
mtree -deU -f BSD.X.dist -p /tmp/MTREE
mtree -bcdjn -F freebsd9 -k uname,gname,mode -p /tmp/MTREE | sed -e 's/ *$//' >BSD.X.new
diff -u BSD.X.dist BSD.X.new
rm -r /tmp/MTREE
```
> mtree: Fix the sort order in BSD.{include,tests}.dist

- bin/test/test.c
- etc/mtree/BSD.include.dist
- etc/mtree/BSD.tests.dist
- sbin/adjkerntz/adjkerntz.8
- sys/dev/gpio/bytgpio.c
- usr.bin/netstat/netstat.1
- usr.sbin/pw/pw.8
Clarify in which formats the _memberlist_ for `groupadd`/`groupmod` can be accepted for `-M`, `-m`, or `-d` flag.
Related commit:	40ab104eaa6f6d5577dcff6d8bf04de03faef345.
> pw: Clarify groupadd/groupmod memberlist formats

- bin/test/test.c
- etc/mtree/BSD.include.dist
- etc/mtree/BSD.tests.dist
- sbin/adjkerntz/adjkerntz.8
- sys/dev/gpio/bytgpio.c
- usr.bin/netstat/netstat.1
- usr.sbin/pw/pw.8
The number of dropped input packets are always shown, the `-d` flag adds the dropped output packets to the output.
> netstat.1: Clarify -d argument

- sys/crypto/siphash/siphash.c
- sys/crypto/siphash/siphash_test.c
This change is required for the first loop iteration of the unit test in siphash_test.c to pass.
The current assert corresponds to an XOR, but it should also allow the case where both values are zero.
I have therefore simplified it to asserting that at least one of the values is zero.
> siphash: allow zero values for final && len in SipBuf()

- usr.sbin/ctld/ctld.c
- usr.sbin/ctld/ctld.h
- usr.sbin/ctld/kernel.c
- usr.sbin/ctld/parse.y
- usr.sbin/ctld/uclparse.c
Separate the parsing of the config file from the reading of kernel port information.  This has three benefits:
* Separation of concerns makes future changes easier.
* Allows the config file to be read earlier, which is necessary for fixing PR 271460.
* Reduces total line count, by eliminating duplication between parse.y (for traditional config file) and uclparse.c (for UCL config file).
MFC after:	2 weeks
Sponsored by:	Axcient
> ctld: parse config file independently of getting kernel info

- sys/cam/ctl/ctl.c
- tests/sys/cam/ctl/Makefile
- tests/sys/cam/ctl/ctl.subr
- tests/sys/cam/ctl/prevent.sh
- tests/sys/cam/ctl/read_buffer.sh
- tests/sys/cam/ctl/start_stop_unit.sh
This is not considered a security risk because the uninitialized data is never directly exposed to user land.  The worse case scenario is that START STOP UNIT might not work correctly.
Also, add ATF tests for START STOP UNIT and PREVENT ALLOW MEDIUM REMOVAL.
This was discussed in https://reviews.freebsd.org/D45952 , but not included as part of that review.
> ctl: fix uninitialized data used by PREVENT ALLOW MEDIUM REMOVAL

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
The struct timespec tv_sec member is of type time_t.  Make sure that all variables related to this member are of the type time_t.  This is important for targets where long is a 32-bit type and time_t a 64-bit type.
> ntptime: Use time_t for tv_sec related variables

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
The error was always returned, even after handling the sysctl, breaking installworld under Linux.
Sponsored by:		https://www.patreon.com/valpackett
> cross-build: fix fake_sysctl/tzsetup

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
Add logic that checks if the code doesn't overflow ACPI_EXTENDED_HID_DEVICE_PATH node when searching for optional strings. If the string is not provided in the device path node default value of "\0" is used.
Upstream PR:	https://bugzilla.tianocore.org/show_bug.cgi?id=4555
Obtained from:	https://github.com/tianocore/edk2/commit/96ed60dfd7d4818a532216d64ee87b13fae5c726
> libefivar: Fix AcpiEx print logic

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
For example, printf("%+i", 1) prints "+1".  However, kvprintf() did print just "1" for this example.  According to PRINTF(3):
A sign must always be placed before a number produced by a signed conversion.
For "%+r" radix conversions, keep the "+" handling as it is, since this is a non-standard conversion.
This change allows to support the ' ' conversion modifier in the future.
> kvprintf(): Fix '+' conversion handling

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
10ms seems to be a little too short for some configurations.
I have two USB devices that needed this change (both Sinowealth mice) to work. From my tests, I could only get the issue to show up on both an `AMD 500 Series Chipset USB 3.1 XHCI Controller` and it's 400 series counterpart. Using other hubs on the system works fine. Note that these hubs work perfectly fine for every other USB device I've tried. I also tried it on two different 500 series controllers, getting the exact same result.
Someone also had a similar issue (I'm 90% sure it was also caused by this) on discord a while ago, and it was fixed by moving the usb device to another hub. I don't have enough info, so I don't know what the problematic device was though.
As a sanity check, I looked at what NetBSD was doing and it …
> usb: increase USB_PORT_RESET_RECOVERY

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
Like GPROC0_SEL, GUSERLDT_SEL also occupies two consecutive entries in segment descriptor table. So logically to specify the second descriptor of GUSERLDT_SEL, it shuld be (GUSERLDT_SEL  + 1).
> amd64: move the right parenthesis to the right place

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
Currently, the wsp driver limits the ability for a single-click (left click) on the touchpad followed by a partial release (finger still on the trackpad). When you single-click then partially release, the trackpad is frozen and you cannot continue movement until you fully release the button and re-touch the trackpad for movement.
This patch provides the ability to continue movement after a single-click has taken place.
The tunable hw.usb.wsp.enable_single_tap_movement (1=enabled by default) has already been created for those that do not want to allow the movement of the trackpad after a single click.
Likewise, the wsp driver does not currently correctly allow the movement of the trackpad using two fingers while a single button is held down: that is to say, during a single-button click, it …
> wsp: multi-finger touchpad improvements

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
Commit e695500d3cb945e62b4591cb68792601ed5c4b46 updated the policy table to match [RFC 6724], which obsoletes [RFC 3484].
Add a reference to [RFC 6724], and mark it up as a technical report (`%R`).
[RFC 3484]: https://www.rfc-editor.org/rfc/rfc3484
[RFC 6724]: https://www.rfc-editor.org/rfc/rfc6724
---
Update the sample ip6addrctl.conf.sample file to match the default policy, currently based on [RFC 6724].
---
> ip6addrctl: Reference RFC 6724 instead

- UPDATING
- lib/libc/net/getaddrinfo.3
- lib/libefivar/efivar-dp-format.c
- sbin/geom/core/geom.8
- sbin/growfs/growfs.8
- share/man/man4/acpi_ged.4
- share/man/man4/gve.4
- share/man/man4/ure.4
- share/man/man4/wsp.4
- share/man/man8/diskless.8
- sys/amd64/amd64/machdep.c
- sys/dev/usb/input/wsp.c
- sys/dev/usb/usb.h
- sys/kern/kern_ntptime.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/dn_sched_fq_pie.c
- tools/build/cross-build/fake_sysctl.c
- usr.bin/du/du.c
- usr.bin/getaddrinfo/getaddrinfo.1
- usr.bin/iscsictl/iscsictl.c
- usr.bin/iscsictl/iscsictl.h
- usr.bin/netstat/main.c
- usr.bin/netstat/netstat.h
- usr.bin/w/w.c
- usr.bin/wc/wc.c
- usr.sbin/adduser/adduser.8
- usr.sbin/ip6addrctl/ip6addrctl.8
- usr.sbin/ip6addrctl/ip6addrctl.conf.sample
- usr.sbin/lastlogin/lastlogin.c
Update the document description language to the more concise form used already by the other USB Ethernet drivers, trimming so that apropos results continue fitting in one line on a standard console.
Update the description section to mention newly added adapters.
Fixes:		6ea4d9
MFC after:	3 days
> ure.4: description consistencies + tag spdx

- release/amd64/make-memstick.sh
- release/amd64/mkisoimages.sh
- share/mk/src.opts.mk
- stand/Makefile
- stand/common/bootstrap.h
- stand/common/load_elf.c
- stand/defs.mk
- stand/efi/Makefile
- stand/efi/Makefile.inc
- stand/efi/libefi32/Makefile
- stand/efi/loader/Makefile
- stand/efi/loader/arch/i386/Makefile.inc
- stand/efi/loader/arch/i386/amd64_tramp.S
- stand/efi/loader/arch/i386/elf64_freebsd.c
- stand/efi/loader/arch/i386/i386.ldscript
- stand/efi/loader/arch/i386/setup.c
- stand/efi/loader/arch/i386/start.S
- stand/efi/loader/bootinfo.c
- stand/efi/loader/conf.c
- stand/efi/loader/copy.c
- stand/efi/loader/framebuffer.c
- stand/efi/loader/main.c
- stand/efi/loader_ia32/Makefile
- sys/amd64/amd64/machdep.c
- sys/x86/include/metadata.h
- tools/boot/install-boot.sh
- tools/build/options/WITHOUT_LOADER_IA32
- tools/build/options/WITH_LOADER_IA32
- usr.sbin/bsdinstall/scripts/bootconfig
Some machines (mostly baytrail notebooks) have 64-bit capable cpus but are stuck on
32-bit uefi firmware, with so CSM.
Add support for them by making the amd64 loader compile itself again with DO32=1,
(see the amd64 Makefile.inc) all of the extra ia32 specific code is in loader/arch/amd64/ia32.
The loader can be disabled using MK_LOADER_IA32.
Tested on qemu and the Acer one 10 s1002
Also cross-compiled to armv6 to make sure nothing broke.
> Add support for 64-bit machines with 32-bit UEFI implementations

- sys/security/mac_veriexec_parser/mac_veriexec_parser.c
- usr.bin/netstat/if.c
- usr.bin/netstat/sctp.c
- usr.sbin/i2c/i2c.c
Resolves [Bug 254672](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254672) and [Bug 244589](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244589)
> netstat: Fix duplicate keys in libxo output

- sys/security/mac_veriexec_parser/mac_veriexec_parser.c
- usr.bin/netstat/if.c
- usr.bin/netstat/sctp.c
- usr.sbin/i2c/i2c.c
NDFREE_PNBUF should be called after checking the return value of vn_open(), and should only be called once.
> mac_veriexec_parser: Fix open_file error handling

- sys/security/mac_veriexec_parser/mac_veriexec_parser.c
- usr.bin/netstat/if.c
- usr.bin/netstat/sctp.c
- usr.sbin/i2c/i2c.c
i2c -sv or i2c -rv prints an uninitialized field i2c_opt.addr. Suppress the verbose message entirely for scan and reset, where it provides no information, and zero initialize the field.
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279261
> i2c: Don't print uninitialized data when verbose

- sys/dev/mfi/mfireg.h
- usr.sbin/mfiutil/mfi_evt.c
PR:		[281155](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281155)
PR:		[281156](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281156)
From my portable mfiutil project, commit <https://sourceforge.net/p/mfiutil/code/ci/d4d66777e4685813cdc501669275bb7853a32088/>.
> mfiutil: Fix incorrect accesses of an union member in 'struct mfi_evt_detail'

- share/man/man7/mitigations.7
- usr.sbin/jail/jail.conf.5
Update related crossreferences and tag paths with the path macro. While here, fix 'one sentance per line rule' and tag spdx.
~~Using xrefs in a document description renders incorrectly in apropos ("jail 8" instead of "jail(8)"). Since mdoc(7) says not to assume that document descriptions can accept child macros, use the string verbatim.~~
MFC after:	3 days
> jail.conf.5: minor cleanup (typos, xrefs, spdx)

- Makefile.inc1
pkg(8) after 8991ebd7afb0 ("Fix #1566: Add pkg-create(8) -l,--level to set compression level") accepts compression level when creating packages with a compression format (e.g. txz, tzst).
When compression is used (PKG_FORMAT is not "tar"), use compression level from PKG_LEVEL for pkg-create(8) to make use of 8991ebd7afb0.
PKG_LEVEL default is set to pkg default to keep current behavior, see pkg(8) 31000cb40b30 ("tzst: by default compression at the 19 level).
https://github.com/freebsd/pkg/commit/8991ebd7afb0
https://github.com/freebsd/pkg/commit/31000cb40b30
https://github.com/freebsd/pkg/blob/b8c3a960b17a/src/create.c#L183
> Makefile.inc1: make pkg-create(8) compression level overridable

- sys/conf/files
ZFS nvpair.c source file depends on XDR unconditionally. This fixes the ZFS build with NFSD kernel options disabled.
> conf: make ZFS depend on XDR sources

- sys/arm/allwinner/a10/a10_intc.c
- sys/arm/arm/exception.S
- sys/arm/arm/gic.c
- sys/arm/arm/gic_acpi.c
- sys/arm/arm/gic_fdt.c
- sys/arm/broadcom/bcm2835/bcm2835_intr.c
- sys/arm/broadcom/bcm2835/bcm2836.c
- sys/arm/ti/aintc.c
- sys/arm64/arm64/exception.S
- sys/arm64/arm64/gic_v3.c
- sys/arm64/arm64/gic_v3_acpi.c
- sys/arm64/arm64/gic_v3_fdt.c
- sys/arm64/arm64/gicv3_its.c
- sys/arm64/include/armreg.h
- sys/arm64/include/intr.h
- sys/kern/pic_if.m
- sys/kern/subr_intr.c
- sys/riscv/riscv/aplic.c
- sys/riscv/riscv/intc.c
- sys/riscv/riscv/sbi_ipi.c
- sys/riscv/riscv/timer.c
- sys/riscv/riscv/trap.c
- sys/sys/intr.h
This adds support for ARM64 fast interrupt requests (FIQs) based off the [suggested approach](https://github.com/strejda/freebsd/commit/396c0b26c33bf99bf660760d68c68c65215b6b3b) in https://reviews.freebsd.org/D40161. Additionally it allows arch-specific code to define the number of interrupt roots supported with `INTR_ROOT_NUM` to avoid changing the number of roots for archs that don't need it. See the individual commit messages for details.
nits: `INTR_ROOT_` was chosen as the prefix to avoid collisions with the unrelated `intr_type` enum but we can bikeshed the name. Also setting up FIQ vectors for ARM64 platforms that don't expect to take FIQ exceptions should be fine, but I'm open to having configs opt-in to FIQ support. I initially considered this but I'm not sure it's worth the …
> Add support for ARM64 FIQs

- usr.bin/vmstat/vmstat.c
The "%lld" format string was used with a value of type long. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278532.
> vmstat: Fix xo_emit format string for percentages

- usr.sbin/efibootmgr/efibootmgr.8
This page was getting pulled into `apropos unix` results due to arguments being on the same line as a name macro in synopsis. While here, tag spdx, fold a line slightly better, add loader.efi(8) to see also and fix it's order.
MFC after:	3 days
> efibootmgr: minor cleanup (spdx, typos, see also)

- sys/sys/soundcard.h
Correct implementation also found in Linux's soundcard.h:
https://github.com/torvalds/linux/blob/master/include/uapi/linux/soundcard.h#L1178
seq_processevent() interprets event[1] as device number and does not
work properly with current SEQ_SYSEX() implementation.
> sound: Fix SEQ_SYSEX() macro

- tools/build/cross-build/include/linux/limits.h
This creates a circular dependency for OpenZFS's libspl in sys/uio.h,
and it shouldn't be needed since the system limits.h already defines
IOV_MAX, so delete it, and unconditionally assert that to be the case.
Otherwise the re-include of libspl's sys/uio.h tries to use PAGESIZE
before it has been defined by OpenZFS's own sys/param.h.
Fixes:		7a7741af18d6 ("zfs: merge openzfs/zfs@b10992582")
MFC after:	1 week
> tools/build/cross-build: Don't include sys/uio.h from linux limits.h

- usr.sbin/ppp/ppp.8
Move [PR #248359](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248359) here as part of a cleanup of personal old bug reports.
> ppp.8: Fix typo cuad0 -> cuau0

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
While trying to resolve some custom installer issues, we found that using conscontrol(8) or setting kern.always_console_output=0 in sysctl.conf(5) did not always prevent console output. This is in part because some areas of the kernel were outputting to the console device without checking the status of the setting. These changes enforce checking of the value in both locations where console output occurs from kernel and init(8) based callouts.
Details on changes:
- Moves check for mute to earlier in sequence to silence kernel output even if EARLY_PRINTF is defined.
- Modifies call prf_putbuf() and prf_putchar() in subr_prf.c to strip TOCONS flag if muting is enabled, to honor the setting at print level.
This is a rather simple change, which increases areas where flags to silence console …
>  Reduce additional console output when muted

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
The bcnt_fwd and bcnt_rev fields are the byte counters, while the pcnt_fwd and pcnt_rev fields are the packet counters.
Fix the comments that were swapped around.
> Fix comment typos in ipfw's struct dyn_data

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
Correct `xatrr_to_extattr` to `xattr_to_extattr`.
> linux(4): Fix typo `xatrr` in function name

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
Printing the file name doesn't make sense since mkstemp failing means that the file wasn't created.
before:
```
$ install existing_file /nonexistent/file
install: /nonexistent/INS@5TLQxk: No such file or directory
```
after:
```
$ install existing_file /nonexistent/file
install: /nonexistent: No such file or directory
```
> install: print directory name instead of file name if mkstemp fails

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
With the new %b format specifier, we need at most 64 characters.
Also, the comment says that we need enough space to write a uintmax_t in octal plus one byte, I'm not sure what that's for. I guess its implying that we need a null terminator(?), but it doesn't look like we do.
This can be easily tested by doing:
```c
printf("%lb\n", 1ul << n); /* Where n is anywhere from 32 to 63 */
```
> libc/stdio: Increase BUF in vfprintf.c and vfwprintf.c

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
Previously, VMXON would be executed on a resume, contrary to proper initalization. The MSR lock may be lost on suspension, therefore must be taken again. Likewise, the VMX Enable bit may be cleared upon suspend, requiring to be re-set.
Concretely disable VMX on suspend, and re-enable it on resume.
Note: any IOMMU context will remain lost for any enabled vmm devices.
> vmm: Correctly suspend and resume the vmm driver.

- bin/sh/sh.1
- lib/libc/stdio/vfprintf.c
- lib/libc/stdio/vfwprintf.c
- share/man/man4/vt.4
- sys/amd64/acpica/acpi_wakeup.c
- sys/amd64/amd64/machdep.c
- sys/amd64/include/cpu.h
- sys/amd64/include/vmm.h
- sys/amd64/vmm/amd/svm.c
- sys/amd64/vmm/intel/vmx.c
- sys/amd64/vmm/vmm.c
- sys/compat/linux/linux_xattr.c
- sys/kern/kern_cons.c
- sys/kern/subr_prf.c
- sys/netpfil/ipfw/ip_fw_dynamic.c
- sys/x86/x86/mp_x86.c
- usr.bin/tip/tip/cu.1
- usr.bin/xinstall/tests/install_test.sh
- usr.bin/xinstall/xinstall.c
When I first discovered the history section of the BSD manual, I knew I had stumbled into a cathedral. In just a few sentances, it provides the reader with a idea of how Chestertons fence came to be there, creating context to begin understanding the deeper spiritual meaning of POLA and consistency in the design philosophy of our community. 
Reinforce this elegance by adding the release when Almquists shell first appeared in BSD. While here, tag spdx and remove a redundant macro.
History source:	www.in-ulm.de/~mascheck/various/ash/#bsd
> sh.1: update history + spdx + linter error

- share/man/man4/uart.4
No information or search keywords are removed because the rendered title will show the acronym first instead of twice.
I think just saying "device" is more elegant than just saying "driver", but it seems like we're moving towards "driver" because it eases the learning curve.
> uart.4: describe better + spdx

- .github/workflows/style.yml
Optimize the style workflow by limiting the fetch depth to the number of commits in the PR + 1. Unfortunately, the only way to add one seems to be to create a new step and do it there.
I conducted a small test here: https://github.com/VexedUXR/freebsd-src/pull/3
This reduces the execution time to ~50s.
Also make it so the workflow only triggers on source files.
> github: optimize style workflow

- share/man/man4/u3g.4
Issue: this is not discoverable in apropos or the release hw notes.
This is a small change but kind of a big deal because potential new users come to our social spaces and nobody thinks there's 4g modems so they say they'll stick with $otheros instead for their router project.
+ add `cellular` and `modem` to manual document description (apropos search keywords)
+ add `cellular` and `modems` to HARDWARE for search in the release hardware notes [^1]
+ massage introductory sentence because 4G and PCIe modems are existing here (but do they operate over usb?)
+ tag spdx
Unresolved questions, hopefully not obstructing this undocumented documentation bugfix:
- what is mpd connections? I don't see that in apropos
- is this ucom thing still the rule or has this aged poorly? How does this relate to …
> u3g.4: increase visibility in apropos and release HW notes

- share/man/man9/style.9
This rolls up all the changes to style 9 not yet merged. Style should generally be the same across all branches.
The SCCS and branch predictor commits are both somewhat manual partial merges altered to only touch style.9.
> MFC style.9 to FreeBSD 14

- tools/build/checkstyle9.pl
Silence the warning about Signed-off-by: lines if the Author: is using a FreeBSD.org address.  We don't require the lines so it's just noise in this case.
> checkstyle9.pl: don't require Signed-off-by for committers

- contrib/mandoc/mdoc.7
FreeBSD Release infrastructure has been generating the Hardware Compatibility Notes from the HARDWARE section in manuals for some decades. Add this section to the STANDARD SECTIONS of the cross platform manual page specification.
The goal of this project is to transform supported hardware discovery over the next 5 years by getting all of the supported hardware into the manual in a consistent, easily discoverable way, and enable higher quality Hardware Release Notes.
Opening this here to get any feedback from our community before trying to send this upstream, so **comments or emoji reactions are extremely helpful**.
Cc @bzfbd @cperciva
> mdoc.7/MANUAL STRUCTURE: add HARDWARE

- usr.bin/sockstat/sockstat.c
Revert a change to the cap_getnameinfo, introduced in 0726c6574f8 and probably unintended, that caused cap_getnameinfo to populate a buffer which was about to be thrown away.
Fixes:		0726c6574f889507e5030173bf4c82c80911394d
> sockstat: microoptimize cap-getnameinfo

- sys/kern/vfs_cache.c
- usr.bin/sockstat/sockstat.1
- usr.bin/sockstat/sockstat.c
The -w flag was previously removed when automatic column sizing was introduced. However, that approach was not compact on small terminal windows, such as 80-column widths.
In this commit, sockstat now uses fixed-width columns by default for cleaner and more compact output. The -w flag has been reintroduced to automatically size the columns, ensuring they are wide enough to fit the longest entry in each column.
Sponsored by:  Google, LLC (GSoC 2025)
MFC after:  2 weeks
> sockstat: Reintroduce -w flag to automatically size the columns

- tests/sys/fs/fusefs/Makefile
Previously the googletest tests would skip themselves if /dev/fuse could not be found.  But that information would not be passed to Kyua. Instead it would think that they had passed.  Also, the atf-sh test would previously fail if the fusefs module weren't loaded.  Now both tests will correctly report their requirements to Kyua.
Note that fusefs's googletest tests still require that the mac_bsdextended(4) module _not_ be loaded, but Kyua has no way to report such a requirement.
MFC after:	2 weeks
> fusefs: report that all tests require the fusefs kernel module

- sys/fs/pseudofs/pseudofs_vnops.c
- sys/fs/smbfs/smbfs_io.c
- sys/fs/smbfs/smbfs_node.h
- sys/fs/smbfs/smbfs_vnops.c
- sys/kern/vfs_subr.c
- sys/kern/vnode_if.src
- sys/sys/vnode.h
- usr.sbin/ctladm/tests/port.sh
Use the standard require.kmods ATF variable instead of ad-hoc code to load the cfiscsi kernel module.
MFC after:	2 weeks
> ctladm: Use require.kmods for cfiscsi

- tests/sys/mac/bsdextended/Makefile
- tests/sys/mac/bsdextended/matches_test.sh
Use the standard required_kmods reporting mechanism to notify Kyua of which kernel modules are required.
MFC after:	2 weeks
> mac_bsdextended: report that all tests require the kernel module

- usr.bin/sockstat/sockstat.c
Revert a change that mistakenly used SCTP path state and the field name `path-state` instead of the correct `conn-state` and `sctp_conn_state()` call. This was introduced in 7b35b4d during the addition of libxo support.
Fixes:		7b35b4d (sockstat: add libxo support)
Reported by:	Phil Shafer <phil@juniper.net>
Sponsored by:	Google, LLC (GSoC 2025)
> sockstat: revert incorrect use of path-state for SCTP connections

- cddl/lib/libspl/Makefile
- sys/contrib/openzfs/lib/libspl/tunables.c
> libspl: Don't build tunables.c when bootstrapping

- usr.bin/sockstat/main.c
The legacy code handling -j in display() was causing xo_finish() to be skipped.  It has also been causing a memory leak since 0726c6574f8 (sockstat: Add automatic column sizing and remove -w option)
Fixes:		7b35b4d1963 (sockstat: add libxo support)
MFC after:	1 week
Reported by:	gleb
> sockstat: fix the -j option with piped output after libxo integration
